/*
 * DbPanel.java
 *
 * Created on December 16, 2008, 1:39 PM
 */

package gblend.db;

import org.jdesktop.application.Action;
import org.jdesktop.application.Application;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ResourceBundle;

import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTree;

/**
 * @author cjjin
 */
public class DbPanel extends JPanel {

  private static final long serialVersionUID = 1L;

  /**
   * Creates new form DbPanel
   */
  public DbPanel() {
    initComponents2();
  }

  public JTree getTree() {
    return schemaTree;
  }
  
   private void initComponents2() {

    JPanel selectPanel = new JPanel();
    dbComboBox = new JComboBox<String>();
    JPanel mainPanel = new JPanel();
    JScrollPane treePane = new JScrollPane();
    schemaTree = new JTree();
    JPanel bottomPanel = new JPanel();
    JButton expandButton = new JButton();
    JButton collapseButton = new JButton();

    setName("Form"); // NOI18N
    setLayout(new BorderLayout());

    selectPanel.setName("selectPanel"); // NOI18N
    selectPanel.setLayout(new BorderLayout());

    dbComboBox.setFocusable(false);
    dbComboBox.setName("DblistComboBox"); // NOI18N
    selectPanel.add(dbComboBox, BorderLayout.CENTER);

    add(selectPanel, BorderLayout.PAGE_START);

    mainPanel.setName("mainPanel"); // NOI18N
    mainPanel.setLayout(new BorderLayout());

    treePane.setName("treePane"); // NOI18N

    schemaTree.setBorder(BorderFactory.createTitledBorder("Unique Graph Labels"));
    //schemaTree.setFont(new Font("Dialog.plain", 0, 14)); // NOI18N
    schemaTree.setFont(new Font("times new roman",Font.BOLD,16));
    schemaTree.setModel(null);
    schemaTree.setDragEnabled(true);
    schemaTree.setName("schemaTree"); // NOI18N
    schemaTree.setShowsRootHandles(true);
    treePane.setViewportView(schemaTree);
    ResourceBundle bundle = ResourceBundle.getBundle("gblend/db/resources/DbPanel"); // NOI18N
    schemaTree.getAccessibleContext().setAccessibleName(bundle.getString("schemaTree.AccessibleContext.accessibleName")); // NOI18N

    mainPanel.add(treePane, BorderLayout.CENTER);

    bottomPanel.setName("bottomPanel"); // NOI18N
    bottomPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));

    ActionMap actionMap = Application.getInstance().getContext().getActionMap(DbPanel.class, this);
    expandButton.setAction(actionMap.get("expandSchemaTree")); // NOI18N
    expandButton.setText(bundle.getString("expandSchemaTree.Action.text")); // NOI18N
    expandButton.setName("expandButton"); // NOI18N
    expandButton.setPreferredSize(new Dimension(25, 25));
    bottomPanel.add(expandButton);

    collapseButton.setAction(actionMap.get("collapseSchemaTree")); // NOI18N
    collapseButton.setText(bundle.getString("collapseSchemaTree.Action.text")); // NOI18N
    collapseButton.setName("collapseButton"); // NOI18N
    collapseButton.setPreferredSize(new Dimension(25, 25));
    bottomPanel.add(collapseButton);

    mainPanel.add(bottomPanel, BorderLayout.PAGE_END);

    add(mainPanel, BorderLayout.CENTER);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("all")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JPanel selectPanel = new JPanel();
    dbComboBox = new JComboBox<String>();
    JPanel mainPanel = new JPanel();
    JScrollPane treePane = new JScrollPane();
    schemaTree = new JTree();
    JPanel bottomPanel = new JPanel();
    JButton expandButton = new JButton();
    JButton collapseButton = new JButton();

    setName("Form"); // NOI18N
    setLayout(new BorderLayout());

    selectPanel.setName("selectPanel"); // NOI18N
    selectPanel.setLayout(new BorderLayout());

    dbComboBox.setFocusable(false);
    dbComboBox.setName("DblistComboBox"); // NOI18N
    selectPanel.add(dbComboBox, BorderLayout.CENTER);

    add(selectPanel, BorderLayout.PAGE_START);

    mainPanel.setName("mainPanel"); // NOI18N
    mainPanel.setLayout(new BorderLayout());

    treePane.setName("treePane"); // NOI18N

    schemaTree.setBorder(BorderFactory.createTitledBorder("Unique Graph Labels"));
    schemaTree.setFont(new Font("Dialog.plain", 0, 12)); // NOI18N
    schemaTree.setModel(null);
    schemaTree.setDragEnabled(true);
    schemaTree.setName("schemaTree"); // NOI18N
    schemaTree.setShowsRootHandles(true);
    treePane.setViewportView(schemaTree);
    ResourceBundle bundle = ResourceBundle.getBundle("gblend/db/resources/DbPanel"); // NOI18N
    schemaTree.getAccessibleContext().setAccessibleName(bundle.getString("schemaTree.AccessibleContext.accessibleName")); // NOI18N

    mainPanel.add(treePane, BorderLayout.CENTER);

    bottomPanel.setName("bottomPanel"); // NOI18N
    bottomPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));

    ActionMap actionMap = Application.getInstance().getContext().getActionMap(DbPanel.class, this);
    expandButton.setAction(actionMap.get("expandSchemaTree")); // NOI18N
    expandButton.setText(bundle.getString("expandSchemaTree.Action.text")); // NOI18N
    expandButton.setName("expandButton"); // NOI18N
    expandButton.setPreferredSize(new Dimension(25, 25));
    bottomPanel.add(expandButton);

    collapseButton.setAction(actionMap.get("collapseSchemaTree")); // NOI18N
    collapseButton.setText(bundle.getString("collapseSchemaTree.Action.text")); // NOI18N
    collapseButton.setName("collapseButton"); // NOI18N
    collapseButton.setPreferredSize(new Dimension(25, 25));
    bottomPanel.add(collapseButton);

    mainPanel.add(bottomPanel, BorderLayout.PAGE_END);

    add(mainPanel, BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  @Action
  public void expandSchemaTree() {
    for (int i = 0; i < schemaTree.getRowCount(); i++) {
      schemaTree.expandRow(i);
    }
  }

  @Action
  public void collapseSchemaTree() {
    for (int i = 0; i < schemaTree.getRowCount(); i++) {
      schemaTree.collapseRow(i);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JComboBox<String> dbComboBox;
  private JTree schemaTree;
  // End of variables declaration//GEN-END:variables

  public JComboBox<String> getDatabaseListComboBox() {
    return dbComboBox;
  }
}
