/*
 * LoadingDialog.java
 *
 * Created on December 18, 2008, 11:19 AM
 */

package gblend.db;

import org.jdesktop.application.Task;

import java.awt.Frame;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ResourceBundle;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import gblend.GBlendApp;
import java.awt.Font;

/**
 * @author cjjin
 */
public class LoadingDialog extends JDialog implements PropertyChangeListener {

  private static final long serialVersionUID = 1L;
  private final Task task;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancelButton;
    private JLabel jLabel;
    private JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

  /**
   * Creates new form LoadingDialog
   */
  public LoadingDialog(Frame parent, Task task) {
    super(parent, true);
    initComponents();
    this.task = task;
    cancelButton.setEnabled(task.getUserCanCancel());
  }

  // @formatter:off
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new JProgressBar();
        jLabel = new JLabel();
        cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ResourceBundle bundle = ResourceBundle.getBundle("gblend/db/resources/LoadingDialog"); // NOI18N
        setTitle(bundle.getString("Form.title")); // NOI18N
        setBounds(new Rectangle(0, 0, 100, 20));
        setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        progressBar.setIndeterminate(true);
        progressBar.setName("progressBar"); // NOI18N

        jLabel.setName("jLabel"); // NOI18N

        cancelButton.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        cancelButton.setText(bundle.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  // @formatter:on

  @SuppressWarnings("UnusedParameters")
  private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    // this.secondaryLabel.setText("Cancelling Task...");
    // this.cancelButton.setEnabled(false);
    task.cancel(true);
    doClose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void doClose() {
    setVisible(false);
    dispose();
  }

  @Override
  public void propertyChange(PropertyChangeEvent evt) {
    String propertyName = evt.getPropertyName();
    // System.out.println(propertyName);
    switch (propertyName) {
      case "started":
        GBlendApp.getApplication().show(this);
        progressBar.setVisible(true);
        progressBar.setIndeterminate(true);
        break;
      case "done":
        setVisible(false);
        break;
      case "message":
        String text = (String) (evt.getNewValue());
        jLabel.setText(text);
        break;
      case "progress":
        int value = (Integer) (evt.getNewValue());
        progressBar.setVisible(true);
        progressBar.setValue(value);
        progressBar.setIndeterminate(true);
        break;
    }
  }
}
