package gblend;

import org.jdesktop.application.Action;
import org.jdesktop.application.Application;

import java.awt.Font;
import java.awt.Frame;
import java.util.ResourceBundle;

import javax.swing.ActionMap;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class GBlendAboutBox extends JDialog {

  private static final long serialVersionUID = 1L;

  public GBlendAboutBox(Frame parent) {
    super(parent);
    initComponents();
    getRootPane().setDefaultButton(closeButton);
  }

  @Action
  public void closeAboutBox() {
    setVisible(false);
    dispose();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    closeButton = new JButton();
    JLabel appTitleLabel = new JLabel();
    JLabel versionLabel = new JLabel();
    JLabel appVersionLabel = new JLabel();
    JLabel vendorLabel = new JLabel();
    JLabel appVendorLabel = new JLabel();
    JLabel homepageLabel = new JLabel();
    JLabel appHomepageLabel = new JLabel();
    JLabel appDescLabel = new JLabel();
    JLabel imageLabel = new JLabel();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    ResourceBundle bundle = ResourceBundle.getBundle("gblend/resources/GBlendAboutBox"); // NOI18N
    setTitle(bundle.getString("title")); // NOI18N
    setModal(true);
    setName("aboutBox"); // NOI18N
    setResizable(false);

    ActionMap actionMap =
        Application.getInstance().getContext().getActionMap(GBlendAboutBox.class, this);
    closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
    closeButton.setText(bundle.getString("closeAboutBox.Action.text")); // NOI18N
    closeButton.setName("closeButton"); // NOI18N

    appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(
      appTitleLabel.getFont().getStyle() | Font.BOLD, appTitleLabel.getFont().getSize() + 2));
    appTitleLabel.setText(bundle.getString("Application.title")); // NOI18N
    appTitleLabel.setName("appTitleLabel"); // NOI18N

    versionLabel.setFont(versionLabel.getFont().deriveFont(
      versionLabel.getFont().getStyle() | Font.BOLD));
    versionLabel.setText(bundle.getString("versionLabel.text")); // NOI18N
    versionLabel.setName("versionLabel"); // NOI18N

    appVersionLabel.setText(bundle.getString("Application.version")); // NOI18N
    appVersionLabel.setName("appVersionLabel"); // NOI18N

    vendorLabel.setFont(vendorLabel.getFont().deriveFont(
      vendorLabel.getFont().getStyle() | Font.BOLD));
    vendorLabel.setText(bundle.getString("vendorLabel.text")); // NOI18N
    vendorLabel.setName("vendorLabel"); // NOI18N

    appVendorLabel.setText(bundle.getString("Application.vendor")); // NOI18N
    appVendorLabel.setName("appVendorLabel"); // NOI18N

    homepageLabel.setFont(homepageLabel.getFont().deriveFont(
      homepageLabel.getFont().getStyle() | Font.BOLD));
    homepageLabel.setText(bundle.getString("homepageLabel.text")); // NOI18N
    homepageLabel.setName("homepageLabel"); // NOI18N

    appHomepageLabel.setText(bundle.getString("Application.homepage")); // NOI18N
    appHomepageLabel.setName("appHomepageLabel"); // NOI18N

    appDescLabel.setText(bundle.getString("appDescLabel.text")); // NOI18N
    appDescLabel.setName("appDescLabel"); // NOI18N

    imageLabel.setName("imageLabel"); // NOI18N

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
      layout
      .createSequentialGroup()
      .addComponent(imageLabel)
      .addGap(18, 18, 18)
      .addGroup(
        layout
        .createParallelGroup(GroupLayout.Alignment.TRAILING)
        .addGroup(
          GroupLayout.Alignment.LEADING,
          layout
          .createSequentialGroup()
          .addGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(versionLabel).addComponent(vendorLabel)
            .addComponent(homepageLabel))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout.createParallelGroup(GroupLayout.Alignment.LEADING)
              .addComponent(appVersionLabel).addComponent(appVendorLabel)
              .addComponent(appHomepageLabel)))
              .addComponent(appTitleLabel, GroupLayout.Alignment.LEADING)
              .addComponent(appDescLabel, GroupLayout.Alignment.LEADING,
                GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE).addComponent(closeButton))
                .addContainerGap()));
    layout.setVerticalGroup(layout
      .createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 193, Short.MAX_VALUE)
      .addGroup(
        layout
        .createSequentialGroup()
        .addContainerGap()
        .addComponent(appTitleLabel)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(appDescLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
          GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(
            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
            .addComponent(versionLabel).addComponent(appVersionLabel))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
              .addComponent(vendorLabel).addComponent(appVendorLabel))
              .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(
                layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(homepageLabel).addComponent(appHomepageLabel))
                .addGap(52, 52, Short.MAX_VALUE).addComponent(closeButton).addContainerGap()));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton closeButton;
  // End of variables declaration//GEN-END:variables

}
