/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.claribole.zgrviewer;

import java.awt.Dimension;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartMouseEvent;
import org.jfree.chart.ChartMouseListener;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.ChartEntity;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author kaihuang
 */
public class BarChart extends javax.swing.JFrame {
    private DefaultCategoryDataset dataset;
    private ChartPanel chartPanel=null;
    private JPanel statisContainer;
    private Vector<List<Integer>> vectorList;
    /**
     * Creates new form BarChart
     */
    public BarChart() {
        initComponents();
    }
     public BarChart(DefaultCategoryDataset data, Vector<List<Integer>> v) {
        initComponents();
        dataset = data;
        vectorList = v;
        createBarChartPane();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	setSize(new Dimension(500, 500));
	setContentPane(statisContainer);
        
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gblend/resources/piechart.png")).getImage());
        setTitle("Result Distributions");
        setVisible(true);
    }
    public void createBarChartPane(){
        JFreeChart barChart = ChartFactory.createBarChart(
            "Number of results","Timestamps","Results",dataset,PlotOrientation.VERTICAL,true, true, true);
       chartPanel = new ChartPanel(barChart);
       ChartMouseListener l = new ChartMouseListener() {
        @Override
        public void chartMouseMoved(ChartMouseEvent e) {
            ChartEntity entity = e.getEntity();  
            if (entity != null) {   
      
                System.out.println("Mouse clicked: " + entity.toString());   
            }   
            else {   
                System.out.println("Mouse clicked: null entity.");   
            }   
        }
        @Override
        public void chartMouseClicked(ChartMouseEvent e) {
            ChartEntity entity = e.getEntity();  
             if (entity != null) {   
               // new PieChartView(String.valueOf(runtimes)).generatePieChart(String.valueOf(runtimes)) ;
                String resultstr = entity.toString();
                String pattern = "columnKey=(\\d+),";
                Pattern r = Pattern.compile(pattern);
                Matcher m = r.matcher(resultstr);
                if (m.find()) {
                   String col = m.group(1);
                   int index = Integer.parseInt(col);
                   List<Integer> idL = vectorList.get(index-1);
                   HashMap<Integer, Integer> hashMap=new HashMap<Integer, Integer>();
                   System.out.println("hashMap size:"+hashMap.size()+" col:"+col);
                   for(Integer t : idL){
                        int k = t/20;
                        if(!hashMap.containsKey(k)){  
                            hashMap.put(k, 1);  
                        }else{  
                            int N=hashMap.get(k)+1;  
                            hashMap.put(k, N);  
                        }  
                   }
                   new PieChartJFrame(hashMap);
                }
               
               System.out.println("Mouse clicked: " + entity.toString());   
            }   
            else {   
                System.out.println("Mouse clicked: null entity.");   
            }   
        }
       };
       chartPanel.addChartMouseListener(l);
       statisContainer = new JPanel();
       statisContainer.removeAll();
       chartPanel.setMaximumSize(new Dimension(400,400));
       chartPanel.setMinimumSize(new Dimension(400,400));
       chartPanel.setPreferredSize(new Dimension(400,400));
       statisContainer.add(chartPanel);
       statisContainer.validate();
       statisContainer.repaint();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
