/*
 * GenPatternsDialog.java
 *
 * Created on Oct 27, 2012, 11:18:45 AM
 */

package gblend.pattern;

import java.awt.Font;
import org.openide.util.NbBundle;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import prague.pattern.PatternSetInfo;

/**
 * @author Andy
 */
public class GenPatternsDialog extends JDialog {

  private boolean returnStatus = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField difNum;
    private JTextField freqNum;
    private JTextField maxPatSize;
    private JTextField minPatSize;
    private JTextField nifNum;
    // End of variables declaration//GEN-END:variables

  /** Creates new form GenPatternsDialog */
  public GenPatternsDialog(Frame parent) {
    super(parent, true);
    initComponents();
  }

  public boolean isOk() {
    return returnStatus;
  }

  public PatternSetInfo getPatternSetInfo() {
    return new PatternSetInfo(Integer.parseInt(freqNum.getText()),
                              Integer.parseInt(difNum.getText()),
                              Integer.parseInt(nifNum.getText()),
                              Integer.parseInt(minPatSize.getText()),
                              Integer.parseInt(maxPatSize.getText()));
  }

  private void closeDialog(boolean retStatus) {
    returnStatus = retStatus;
    setVisible(false);
    dispose();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel panel = new JPanel();
        JLabel minLabel = new JLabel();
        minPatSize = new JTextField();
        JLabel maxLabel = new JLabel();
        maxPatSize = new JTextField();
        JLabel freqLabel = new JLabel();
        freqNum = new JTextField();
        JLabel difLabel = new JLabel();
        difNum = new JTextField();
        JLabel nifLabel = new JLabel();
        nifNum = new JTextField();
        JButton genButton = new JButton();
        JButton cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.panel.border.title")); // NOI18N
        setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        setResizable(false);

        panel.setBorder(BorderFactory.createTitledBorder(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.panel.border.title"))); // NOI18N
        panel.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        panel.setName("panel"); // NOI18N

        minLabel.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        minLabel.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.minLabel.text")); // NOI18N
        minLabel.setName("minLabel"); // NOI18N

        minPatSize.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        minPatSize.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.minPatSize.text")); // NOI18N
        minPatSize.setName("minPatSize"); // NOI18N

        maxLabel.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        maxLabel.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.maxLabel.text")); // NOI18N
        maxLabel.setName("maxLabel"); // NOI18N

        maxPatSize.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        maxPatSize.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.maxPatSize.text")); // NOI18N
        maxPatSize.setName("maxPatSize"); // NOI18N

        freqLabel.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        freqLabel.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.freqLabel.text")); // NOI18N
        freqLabel.setName("freqLabel"); // NOI18N

        freqNum.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        freqNum.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.freqNum.text")); // NOI18N
        freqNum.setName("freqNum"); // NOI18N

        difLabel.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        difLabel.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.difLabel.text")); // NOI18N
        difLabel.setName("difLabel"); // NOI18N

        difNum.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        difNum.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.difNum.text")); // NOI18N
        difNum.setName("difNum"); // NOI18N

        nifLabel.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        nifLabel.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.nifLabel.text")); // NOI18N
        nifLabel.setName("nifLabel"); // NOI18N

        nifNum.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        nifNum.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.nifNum.text")); // NOI18N
        nifNum.setName("nifNum"); // NOI18N

        GroupLayout panelLayout = new GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(minLabel)
                            .addComponent(maxLabel))
                        .addGap(131, 131, 131)
                        .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(minPatSize, GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(maxPatSize, GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(freqLabel)
                        .addGap(29, 29, 29)
                        .addComponent(freqNum, GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(nifLabel)
                            .addComponent(difLabel))
                        .addGap(38, 38, 38)
                        .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(difNum, GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(nifNum, GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(minLabel)
                    .addComponent(minPatSize, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(maxLabel)
                    .addComponent(maxPatSize, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(freqLabel)
                    .addComponent(freqNum, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(difNum, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(difLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(nifLabel)
                    .addComponent(nifNum, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        genButton.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        genButton.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.genButton.text")); // NOI18N
        genButton.setName("genButton"); // NOI18N
        genButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                genButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        cancelButton.setText(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(genButton)
                        .addGap(29, 29, 29)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(genButton)
                    .addComponent(cancelButton))
                .addGap(20, 20, 20))
        );

        panel.getAccessibleContext().setAccessibleDescription(NbBundle.getMessage(GenPatternsDialog.class, "GenPatternsDialog.panel.AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

  @SuppressWarnings("UnusedParameters")
  private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    closeDialog(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

  @SuppressWarnings("UnusedParameters")
  private void genButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_genButtonActionPerformed
    closeDialog(true);
  }//GEN-LAST:event_genButtonActionPerformed

}
